"""Metrics, efficiency profiling, figures, and training-loop infrastructure."""

from src.utils.efficiency import (
    EfficiencyReport,
    LatencyReport,
    ParameterReport,
    benchmark_latency,
    count_parameters,
    estimate_flops,
    parameter_report,
    profile_model,
    top_k_saving,
)
from src.utils.evaluation import (
    REQUESTED_COLUMNS,
    RunSummary,
    collect_run_summaries,
    load_test_predictions,
    save_publication_figures,
    save_test_predictions,
    write_summary_csv,
)
from src.utils.metrics import (
    AlignmentReport,
    ClassMetrics,
    HierarchicalEvaluation,
    classification_metrics,
    confusion_matrices,
    evaluate_hierarchical,
    expert_utilization_counts,
    kl_alignment_rate,
    misclassification_rates,
    per_class_metrics,
    roc_auc_ovr,
    tsne_projection,
)
from src.utils.visualization import (
    denormalize_images,
    make_image_grid,
    plot_confusion_matrix,
    plot_expert_utilization,
    plot_loss_curves,
    plot_metric_heatmap,
    plot_misclassification_rates,
    plot_tsne,
    save_figure,
)

__all__ = [
    "REQUESTED_COLUMNS",
    "AlignmentReport",
    "ClassMetrics",
    "EfficiencyReport",
    "HierarchicalEvaluation",
    "LatencyReport",
    "ParameterReport",
    "RunSummary",
    "benchmark_latency",
    "classification_metrics",
    "collect_run_summaries",
    "confusion_matrices",
    "count_parameters",
    "denormalize_images",
    "estimate_flops",
    "evaluate_hierarchical",
    "expert_utilization_counts",
    "kl_alignment_rate",
    "load_test_predictions",
    "make_image_grid",
    "misclassification_rates",
    "parameter_report",
    "per_class_metrics",
    "plot_confusion_matrix",
    "plot_expert_utilization",
    "plot_loss_curves",
    "plot_metric_heatmap",
    "plot_misclassification_rates",
    "plot_tsne",
    "profile_model",
    "roc_auc_ovr",
    "save_figure",
    "save_publication_figures",
    "save_test_predictions",
    "top_k_saving",
    "tsne_projection",
    "write_summary_csv",
]
