"""Model definitions for the hierarchical seed classifier (paper Sections 4-5)."""

from src.models.backbones.swinv2_dino import DINO, DINOHead
from src.models.baselines import (
    BASELINE_MODELS,
    FlatSupervisedBaseline,
    IdentityEncoder,
    LinearProbeHead,
    build_baseline,
    build_linear_probe,
)
from src.models.builder import (
    PAPER_EMBED_DIM,
    SUB_HEAD_VARIANTS,
    TOKEN_MODES,
    BackboneFeatureExtractor,
    DinoV2SwinV2Encoder,
    HierarchicalOutput,
    HierarchicalSeedClassifier,
    build_encoder,
    build_feature_extractor,
    build_hierarchical_moe,
    validate_swinv2_name,
)
from src.models.components import (
    ArcFaceHead,
    CrossAttention,
    DenseExpertBlock,
    EmbeddingProjection,
    FiLMFusion,
    LayerScale,
    LinearSubVarietyHead,
    NormFaceHead,
    MixtureOfExperts,
    MoEOutput,
    SeedTypeClassifier,
    SeedTypeProjection,
    SubVarietyEmbedding,
    TokenPooling,
    TransformerExpert,
)

__all__ = [
    "BASELINE_MODELS",
    "DINO",
    "PAPER_EMBED_DIM",
    "SUB_HEAD_VARIANTS",
    "TOKEN_MODES",
    "ArcFaceHead",
    "BackboneFeatureExtractor",
    "CrossAttention",
    "DINOHead",
    "DenseExpertBlock",
    "DinoV2SwinV2Encoder",
    "EmbeddingProjection",
    "FiLMFusion",
    "FlatSupervisedBaseline",
    "HierarchicalOutput",
    "HierarchicalSeedClassifier",
    "IdentityEncoder",
    "LayerScale",
    "LinearProbeHead",
    "LinearSubVarietyHead",
    "MixtureOfExperts",
    "MoEOutput",
    "NormFaceHead",
    "SeedTypeClassifier",
    "SeedTypeProjection",
    "SubVarietyEmbedding",
    "TokenPooling",
    "TransformerExpert",
    "build_baseline",
    "build_encoder",
    "build_feature_extractor",
    "build_hierarchical_moe",
    "build_linear_probe",
    "validate_swinv2_name",
]
